### ISSUE TITLE
Article `download()` failed with 404 Client Error

### ISSUE THREAD

**Issue by harishaaram** [codelucas/newspaper#444] opened 2017-09-23 19:47 UTC
Hi,

I keep getting this error message - **Article `download()` failed with 404 Client Error: Not Found for url: http://www.foxnews.com/2017/09/22/sheriff-clarke-trump-wins-either-way-luther-strange-roy-moore-alabama-senate-race on URL http://www.foxnews.com/2017/09/22/sheriff-clarke-trump-wins-either-way-luther-strange-roy-moore-alabama-senate-race**

It happens for various article url links.

Here is the code i am using,
`news_content = newspaper.build(url)
    for eachArticle in news_content.articles:
        i = i +1
        article = news_content.articles[i]

        article.download()#now download and parse each articles
        article.parse()

        article.nlp()

        backupfile.write("\n"+ "--------------------------------------------------------------" + "\n")
        backupfile.write(str(article.keywords))

        datasetfile.write("\n" + "----SUMMARY ARTICLE-> No. " + str(i) + "\n")
        datasetfile.write(article.summary) #only summary of the article is written in the dataset directory

        backupfile.write("\n"+"----SUMMARY ARTICLE---" + "\n")
        backupfile.write(article.summary)
        backupfile.write("\n"+"----TEXT INSIDE ARTICLE---" + "\n")
        backupfile.write(article.text)
        time.sleep(2)`

Attached below is the screenshot of the error,
![screenshot from 2017-09-23 14-46-29](https://user-images.githubusercontent.com/16678684/30776553-0a94f7f8-a06e-11e7-854a-922a08d683c4.png)

**Comment by vaishnavm217** [comment] 2017-10-03 17:21
One of my colleagues had the same problem. She striped off newline character in the url strings using ```url.strip()``` and the error stopped.

**Comment by jrunrun** [comment] 2017-10-03 18:00
Similar issue, was hoping to skip over the errors with some exception handling.

Issue:
I create an object "cnn" and try to iterate across it. One of the URL's is returning a 404. I have confirmed that it is a bad URL. I want to the next article in the for loop. I've tried a few exception handling methods, but no luck.

The below code does not skip the exception. Can you tell me what I'm doing wrong?

----- code below ---

cnn = newspaper.build('http://www.cnn.com/', memoize_articles=False)

for article in cnn.articles:
    
    # Try-Except-Continue will skip to the next article in the For loop if there is an exception
    try:
        article.download()
    except ArticleException:
        continue
        
    article.parse()
    article.nlp()

**Comment by vaishnavm217** [comment] 2017-10-03 18:11
best workaround is just to use ``` except: ``` rather than specifying the exception

**Comment by jrunrun** [comment] 2017-10-04 18:18
PLEASE ADVISE -- THIS EXCEPTION HANDLING DOES NOT WORK.

CODE:
import newspaper

cnn = newspaper.build('http://www.cnn.com/', memoize_articles=False)

for article in cnn.articles:
        
        # Try-Except-Continue will skip to the next article in the For loop if there is an exception
    try:
        article.download()
    except:
        continue
        
    article.parse()
    article.nlp()
    
ERROR:
Article `download()` failed with 404 Client Error: Not Found for url: http://www.cnn.com/hln-morning-express-tour-robin-meade on URL http://www.cnn.com/hln-morning-express-tour-robin-meade

**Comment by vaishnavm217** [comment] 2017-10-04 22:28
> THIS EXCEPTION HANDLING DOES NOT WORK.

It won't work as it is hardcoded there, not raising error.

> I create an object "cnn" and try to iterate across it. One of the URL's is returning a 404. I have confirmed that it is a bad URL. 

if this still gives the download error, try striping the newline characters using `strip()` method

for better debugging, try running these lines in python terminal(try for one link). if it doesn't give the same error then it should be newline characters

**Comment by jrunrun** [comment] 2017-10-05 15:48
url.strip() will not fix a bad URL. See URL above returned by cnn object. Click on it. It is a bad URL.

First you told me just to do "except:" now you are telling me there is no error handling?

**Comment by soumenganguly** [comment] 2018-08-06 14:17
Hi,

Did you guys manage to figure this out? 

I am also getting a 410 client error while trying to download an article which, apparently, was removed by the news publisher. And, I couldn't find a way to bypass this article and move on to the next one. I cannot handle the ArticleException. 

Any suggestion to sort this out would be appreciated. 

Great work on the module!

**Comment by rschafish** [comment] 2018-08-06 16:55
suggest you review python documentation for handling exceptions...here is a link, look at Section 8.2 
  Exceptions
https://docs.python.org/3/tutorial/errors.html  

cheers, BobS

**Comment by soumenganguly** [comment] 2018-08-06 19:27
If you've come across this same issue or if you've seen the comments above, you'd realize that this exception is 'hardcoded' within the module and the standard python exception handling doesn't seem to work here. 

If you've been able to resolve this with exception handling then please let me know. Maybe I am doing something wrong. 

Cheers,
Drogpa

**Comment by moosemachineDK** [comment] 2018-08-30 03:44
I just used a simple try/except structure. Seems to work just fine (at least for the 404 error code I was seeing)

`try:
        article.download()
        article.parse()
        article2 = article.text.split()
    except:
        print('***FAILED TO DOWNLOAD***', article.url)
        continue`

**Comment by moosemachineDK** [comment] 2018-08-30 03:45
I just used a simple try except structure. Seems to works just fine (at least for the 404 error I was seeing)


try:
        article.download()
        article.parse()
        article2 = article.text.split()
    except:
        print('***FAILED TO DOWNLOAD***', article.url)
        continue

**Comment by moosemachineDK** [comment] 2018-08-30 03:50
I just used a simple try except structure. Seems to works just fine (at least for the 404 error I was seeing)(code below - don't mind the splitting and stuff' :-))

```

    try:
        article.download()
        article.parse()
        article2 = article.text.split()
    except:
        print('***FAILED TO DOWNLOAD***', article.url)
        continue

```

**Comment by codelucas** [comment] 2018-08-30 07:57
Hello @harishaaram, @jrunrun, and @vaishnavm217: thanks so much for using this library!

The `Exception` you are seeing is outputted on `parse()` or `nlp()` and **not** `download()`, `download()` does not raise this exception, apologies, the error message is confusing and I will fix it.

To fix your exception handling, also put `parse` and `nlp` inside the try/catch statement.

Here is where the exception is thrown: https://github.com/codelucas/newspaper/blob/e34c777e60024111a8949b8f09d42fdf937297c6/newspaper/article.py#L184-L185

**Comment by codelucas** [comment] 2018-08-30 07:59
Hey guys, I am going to close the issue as the fix is posted, but please re-open if you see problems

**Closed by codelucas** 2018-08-30 07:59 UTC
Labels: bug

**Comment by PandaWhoCodes** [comment] 2019-06-26 18:21
I got it to work by changing the user-agent
```
from newspaper import Article
from newspaper import Config

user_agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36'
config = Config()
config.browser_user_agent = user_agent
page = Article("https://www.forbes.com/sites/louiscolumbus/2015/07/13/ten-ways-big-data-is-revolutionizing-supply-chain-management", config=config)
page.download()
page.parse()
print(page.text)
```

**Comment by akoua** [comment] 2019-09-27 05:08
I see the problem, you must remove the double quote in url so make that:
# or, if they only occur at start and end...
      a = a.strip(' \" ') 
It solve my issue

**Comment by monajalal** [comment] 2020-07-23 18:16
@codelucas 
I am able to see this URL in Web Browser however, I cannot download it. Could you please guide me how to fix it?

```
from newspaper import Article
from newspaper import Config

user_agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36'
config = Config()

config.browser_user_agent = user_agent
url = "https://www.newsweek.com/new-mexico-compound-charges-dropped-children-1096830".strip()



page = Article(url, config=config)


page.download()
page.parse()
print(page.text)


```

I initially used exception handling but I definitely need to download the text.

**Comment by monajalal** [comment] 2020-07-23 18:31
I posted the solution here:

```
from newspaper import Article
from newspaper import Config

user_agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:78.0) Gecko/20100101 Firefox/78.0'
config = Config()

config.browser_user_agent = user_agent
url = "https://www.newsweek.com/new-mexico-compound-charges-dropped-children-1096830".strip()



page = Article(url, config=config)


page.download()
page.parse()
print(page.text)
```

Here is the link: https://stackoverflow.com/a/63060794/2414957

**Comment by maralzar** [comment] 2023-06-22 11:23
I have still problem.
from newspaper import Article
```
from newspaper import Config

user_agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:78.0) Gecko/20100101 Firefox/78.0'
config = Config()

config.browser_user_agent = user_agent
url = "https://artificialcorner.com/privategpt-a-free-chatgpt-alternative-to-interact-with-your-documents-offline-ea1c98f98062".strip()



page = Article(url, config=config)


page.download()
page.parse()
print(page.text)
```
output:
--------------------------------------------------------------------------
```
ArticleException                          Traceback (most recent call last)
Cell In[8], line 16
     12 page = Article(url, config=config)
     15 page.download()
---> 16 page.parse()
     17 print(page.text)

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/newspaper/article.py:191, in Article.parse(self)
    190 def parse(self):
--> 191     self.throw_if_not_downloaded_verbose()
    193     self.doc = self.config.get_parser().fromstring(self.html)
    194     self.clean_doc = copy.deepcopy(self.doc)

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/newspaper/article.py:531, in Article.throw_if_not_downloaded_verbose(self)
    529     raise ArticleException('You must `download()` an article first!')
    530 elif self.download_state == ArticleDownloadState.FAILED_RESPONSE:
--> 531     raise ArticleException('Article `download()` failed with %s on URL %s' %
    532           (self.download_exception_msg, self.url))

ArticleException: Article `download()` failed with 403 Client Error: Forbidden for url: https://artificialcorner.com/privategpt-a-free-chatgpt-alternative-to-interact-with-your-documents-offline-ea1c98f98062 on URL https://artificialcorner.com/privategpt-a-free-chatgpt-alternative-to-interact-with-your-documents-offline-ea1c98f98062
```

**Comment by yaba** [comment] 2023-10-09 12:26
I'm having the same issue. Same URL works on browser, curl, and with a simple Python request. Keep getting 404 with newspaper3k. Any news about this ?

**Comment by PandaWhoCodes** [comment] 2023-10-09 13:25
if its just getting the text that you want to do, Since you already get information from curl and python request

then use newspaper's , full_text
```

from newspaper import fulltext  
text = fulltext(html_content)
```
