### ISSUE TITLE
different between demo website and python code

### ISSUE THREAD

**Issue by moveurbody** [codelucas/newspaper#435] opened 2017-09-11 04:34 UTC
Hi,

I use your demo web site to extract a CNN news, but I found the results are different.
The url is [http://edition.cnn.com/2014/03/27/sport/brooklyn-nets-owner-russia/index.html](http://edition.cnn.com/2014/03/27/sport/brooklyn-nets-owner-russia/index.html)

By your demo [website](http://newspaper-demo.herokuapp.com/articles/show?url_to_clean=http%3A%2F%2Fedition.cnn.com%2F2014%2F03%2F27%2Fsport%2Fbrooklyn-nets-owner-russia%2Findex.html), it will show 

> Pro basketball is a staple of American athletics....

 But I use python to get text by "Article.text", it will show 

> Story highlights Russian billionaire owner of Nets considers ownership move to Russian jurisdiction
> 
> The move is "not in any way tying it to the current political situation," the owner's rep said
> 
> Obama signed an order that can target Russian companies vital to its economy
> 
> Pro basketball is a staple of American athletics, taking its place with Major...

Did I use the wrong method?
My python is 3.6 and newspaper3k is 0.2.2.
```
from newspaper import Article

def news_extract(news_url):
    article = Article(news_url, fetch_images=False,)
    article.download()
    article.parse()
    text = article.text
    print(text)

source = 'http://edition.cnn.com/2014/03/27/sport/brooklyn-nets-owner-russia/index.html'
news_extract(source)
```

Thank you

**Comment by antoligy** [comment] 2017-09-11 20:42
Hey, I think you might want to call `article.nlp()` and then access the content via `article.summary`?

**Comment by moveurbody** [comment] 2017-09-12 05:05
Hi,
I want to get the main news content only.
From the demo web site, it can show what I want.

But when I use `Article.text`, it not only shows **_main news content_** but also shows _**story highlights**_.

**By `Article.text`**
> story highlights
> Story highlights Russian billionaire owner of Nets considers ownership move to Russian jurisdiction
> The move is "not in any way tying it to the current political situation," the owner's rep said
> Obama signed an order that can target Russian companies vital to its economy
>
> Pro basketball is a staple of American athletics, taking its place with Major League Baseball and the National Football League as one of the pre-eminent U.S. sports leagues. And it's big business, too, pumping tens of millions of dollars into the U.S. economy.
> So the owner of the Brooklyn Nets raised eyebrows this week when he said he planned to transfer ownership of the team to a company in Russia -- at a time when tension between the U.S. and Russia is at its highest level since the end of the Cold War.
> That raised two questions: Will it happen? Does it matter?
> The billionaire owner, Mikhail Prokhorov, Monday reiterated his year-old intention to transfer the Brooklyn Nets ownership base to Russia, but has since toned down his rhetoric.

**By demo web**
`'Pro basketball is a staple of American athletics, taking its place with Major League Baseball and the National Football League as one of the pre-eminent U.S. sports leagues. And it\'s big business, too, pumping tens of millions of dollars into the U.S. economy.\n\nSo the owner of the Brooklyn Nets raised eyebrows this week when he said he planned to transfer ownership of the team to a company in Russia -- at a time when tension between the U.S. and Russia is at its highest level since the end of the Cold War.\n\nThat raised two questions: Will it happen? Does it matter?\n\nThe billionaire owner, Mikhail Prokhorov, Monday reiterated his year-old intention to transfer the Brooklyn Nets ownership base to Russia, but has since toned down his rhetoric.\n\n"This is a long process which may or may not come to fruition and nothing is imminent," Prokhorov\'s company, Onexim Sports and Entertainment, which owns the NBA basketball team, said in a statement released via the Brooklyn Nets. "Of course, no steps in this direction could or would be taken without the full knowledge and approval of the NBA."\n\nOn Monday, the 48 year-old Russian national told reporters in Moscow, "I have already stated that I will transfer the basketball club (under the Russian jurisdiction)," according to Russian news agency ITAR-Tass.\n\nNot so fast, the NBA said, telling CNN the transfer has yet to begin.\n\n"The Nets are owned by Mikhail Prokhorov through a U.S.-based company," Mike Bass, executive vice president of NBA communications, told CNN. "We have received no official application, nor is there a process under way through our office to transfer the ownership of the Nets to another company."\n\nIf an application to change ownership was submitted by the Nets, 75% of NBA team owners -- or 23 of 30 -- would have to approve the move, Bass said. He said that the NBA\'s Board of Governors (the 30 team owners) would have to decide whether there are any issues with the transfer of ownership application.\n\nCurrently, the NBA has no rules prohibiting a foreign company from owning an NBA team.\n\nThe back-and-`

**Comment by yprez** [comment] 2017-09-12 12:44
@moveurbody I think that the demo website runs on an older version of newspaper (on the python-2 branch). This should explain the different results you're getting...

**Comment by codelucas** [comment] 2017-09-14 01:03
@yprez found the root cause for your inconsistency. It's sad that this is a regression and we should also work on improving extraction accuracy. I am closing this and separately investigating how to improve accuracy.

**Comment by codelucas** [comment] 2017-09-14 01:03
Thanks for filing @moveurbody

**Closed by codelucas** 2017-09-14 01:03 UTC
